function Hd = tianxian700M_70M_10M
%TIANXIAN700M_70M_10M Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 16-May-2018 16:20:09

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in MHz.
Fs = 700;  % Sampling Frequency

Fstop1 = 55;          % First Stopband Frequency
Fpass1 = 65;          % First Passband Frequency
Fpass2 = 75;          % Second Passband Frequency
Fstop2 = 85;          % Second Stopband Frequency
Astop1 = 60;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 80;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
